# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces_ui/change_playlist_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.playlists = QtWidgets.QComboBox(self.widget)
        self.playlists.setObjectName("playlists")
        self.verticalLayout.addWidget(self.playlists)
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.add_song_in_playlist = QtWidgets.QPushButton(self.widget)
        self.add_song_in_playlist.setObjectName("add_song_in_playlist")
        self.verticalLayout_2.addWidget(self.add_song_in_playlist)
        self.delete_playlist_btn = QtWidgets.QPushButton(self.widget)
        self.delete_playlist_btn.setObjectName("delete_playlist_btn")
        self.verticalLayout_2.addWidget(self.delete_playlist_btn)
        self.delete_song_btn = QtWidgets.QPushButton(self.widget)
        self.delete_song_btn.setObjectName("delete_song_btn")
        self.verticalLayout_2.addWidget(self.delete_song_btn)
        self.open_playlist = QtWidgets.QPushButton(self.widget)
        self.open_playlist.setObjectName("open_playlist")
        self.verticalLayout_2.addWidget(self.open_playlist)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменить или открыть плейлист"))
        self.add_song_in_playlist.setText(_translate("Form", "Добавить песню в выбранный плейлист"))
        self.delete_playlist_btn.setText(_translate("Form", "Удалить выбранный плейлист"))
        self.delete_song_btn.setText(_translate("Form", "Удалить песню"))
        self.open_playlist.setText(_translate("Form", "Открыть"))
