# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces_ui/save_playlist_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 194)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.playlist_name = QtWidgets.QLineEdit(self.widget)
        self.playlist_name.setObjectName("playlist_name")
        self.verticalLayout.addWidget(self.playlist_name)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.save_btn = QtWidgets.QPushButton(self.widget)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout_2.addWidget(self.save_btn)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Сохранить плейлист"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">Какое имя дадим плейлисту?</p></body></html>"))
        self.save_btn.setText(_translate("Form", "Сохранить"))
