# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces_ui/signin_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(507, 376)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.login = QtWidgets.QLineEdit(self.widget)
        self.login.setObjectName("login")
        self.horizontalLayout.addWidget(self.login)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setObjectName("password")
        self.horizontalLayout_2.addWidget(self.password)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.error_label = QtWidgets.QLabel(self.widget)
        self.error_label.setObjectName("error_label")
        self.verticalLayout_2.addWidget(self.error_label)
        self.signin_btn = QtWidgets.QPushButton(self.widget)
        self.signin_btn.setObjectName("signin_btn")
        self.verticalLayout_2.addWidget(self.signin_btn)
        self.open_register_btn = QtWidgets.QPushButton(self.widget)
        self.open_register_btn.setObjectName("open_register_btn")
        self.verticalLayout_2.addWidget(self.open_register_btn)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вход"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Вход</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "Логин:  "))
        self.label_3.setText(_translate("Form", "Пароль:"))
        self.checkBox.setText(_translate("Form", "Показать пароль"))
        self.error_label.setText(_translate("Form", "TextLabel"))
        self.signin_btn.setText(_translate("Form", "Войти"))
        self.open_register_btn.setText(_translate("Form", "Не зарегестрированы? Зарегестрироваться"))
